// Firebase Helper File
//Do not edit this file


/* Firebase Authentication */

// Sign up a user
function signUp(email, password) {
  firebase.auth().createUserWithEmailAndPassword(email, password).catch(function(error) {
    // Handle Errors here.
    var errorCode = error.code;
    var errorMessage = error.message;
    console.log(`Error occured in signing up \nError Code : ${errorCode}\nError Message : ${errorMessage}`);
  });
}

// Sign in a user
function signIn(email, password) {
  firebase.auth().signInWithEmailAndPassword(email, password).catch(function(error) {
    // Handle Errors here.
    var errorCode = error.code;
    var errorMessage = error.message;
    console.log(`Error occured in signing in \nError Code : ${errorCode}\nError Message : ${errorMessage}`);
  });
  email - password.html
}

// Firebase Auth Change Listener
firebase.auth().onAuthStateChanged(function(user) {
  if (user) {
    // User is signed in.
    userIsSignedIn(user);
  } else {
    // User is signed out.
    userIsSignedOut();
  }
});


/* Firebase Database*/

var database = firebase.database();

// Read to Firebase Database
function readData(dbRef) {
  firebase.database().ref(dbRef).once('value').then(function(snapshot) {
    return snapshot.val()
  });
}

// Write to Firebase Database
function writeData(dbRef, jsonObject) {
  firebase.database().ref(dbRef).set(jsonObject);
}
